version: "3.8"

services:
  app1_fajrina:
    build: .
    container_name: parkir_app1_fajrina
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      DB_HOST: host_fajrina
      DB_DATABASE: db_fajrina
      DB_USERNAME: root
      DB_PASSWORD: fajrina_secret123
    depends_on:
      - host_fajrina
    networks:
      - asat-net

  app2_fajrina:
    build: .
    container_name: parkir_app2_fajrina
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      DB_HOST: host_fajrina
      DB_DATABASE: db_fajrina
      DB_USERNAME: root
      DB_PASSWORD: fajrina_secret123
    depends_on:
      - host_fajrina
    networks:
      - asat-net

  app3_fajrina:
    build: .
    container_name: parkir_app3_fajrina
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      DB_HOST: host_fajrina
      DB_DATABASE: db_fajrina
      DB_USERNAME: root
      DB_PASSWORD: fajrina_secret123
    depends_on:
      - host_fajrina
    networks:
      - asat-net

  host_fajrina:
    image: mysql:8.0
    container_name: parkir_db_fajrina
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: fajrina_secret123
      MYSQL_DATABASE: db_fajrina
    ports:
      - "33061:3306"
    volumes:
      - dbdata_fajrina:/var/lib/mysql
    networks:
      - asat-net

networks:
  asat-net:
    driver: bridge

volumes:
  asat-vol:
